export default [
  {
    title: "Team Lead - UI / UX Developer",
    company: "Indiana Interactive",
    location: "Indianapolis, IN",
    start_date: "November 2017",
    end_date: "Present",
    keyPoints: [
      "Led teams building diverse web applications for the state of Indiana",
      "Revamped process for bundling and deploying applications",
      "Designed and developed complex web applications that simplified the user's interactions",
      "Helped architect a new framework to build extensible applications",
      "Maintained frameworks and building tools centered on developer experience",
      "Revamped CI/CD pipeline for docker applications",
    ],
    languages: "JavaScript, VueJS, Node, HTML, SCSS",
  },
  {
    title: "Senior Backend Web Developer",
    company: "Force Communications",
    start_date: "Feb 2016",
    location: "Indianapolis, IN",
    end_date: "November 2017",
    keyPoints: [
      "Developed web applications with complex business rules",
      "Managed web application servers and CI/CD Pipelines",
      "Used API driven development to build Laravel and Vue.js applications",
      "Directly worked with clients to provide the best possible solutions to fit their needs",
      "Responsible for building a team to use best practices of Agile and software development",
    ],
    languages: "PHP, JavaScript, HTML, SCSS",
  },
  {
    title: "Software Engineer",
    company: "Patronpath / Verge Ventures",
    location: "Indianapolis, IN",
    start_date: "December 2014",
    end_date: "February 2016",
    keyPoints: [
      "Successfully launched a new online ordering platform serving thousands of orders per day",
      "Lead a small agile team to develop a new online ordering platform with Laravel",
      "Developed dynamic workflows and designs for online ordering",
      "Maintained and supported the legacy online ordering platform",
    ],
    languages: "PHP, JavaScript, HTML, SCSS",
  },
  {
    title: "Web Developer",
    company: "NTSupply",
    location: "Greenwood, IN",
    start_date: "May 2014",
    end_date: "December 2014",
    keyPoints: [
      "Developed custom content management system",
      "Designed email integration for DiscountFilters.com",
      "Debugged and improved performance of web applications",
    ],
    languages: "PHP, JavaScript, HTML, CSS",
  },
  {
    title: "Web Developer",
    company: "Purdue University – ITaP Research Computing",
    location: "West Lafayette, IN",
    start_date: "September 2013",
    end_date: "May 2014",
    keyPoints: ["Developed JavaScript tools for driNET.hubzero.org"],
    languages: "PHP, JavaScript, HTML, CSS",
  },
  {
    title: "Web Developer",
    company: "Envision Center",
    location: "West Lafayette, IN",
    start_date: "September 2013",
    end_date: "May 2014",
    keyPoints: [
      "Worked with ArcGIS JavaScript API to develop interactive maps",
    ],
    languages: "PHP, JavaScript, HTML, CSS",
  },
  {
    title: "Developer -> Senior Developer",
    company: "ResNet",
    location: "West Lafayette, IN",
    start_date: "August 2009",
    end_date: "August 2013",
    keyPoints: [
      "Lead the design, development, and successful launch of rewritten web applications",
    ],
    languages: "PHP, Javascript",
  },
];
