export default [
  {
    title: "Team Lead - UI / UX Developer",
    company: "Indiana Interactive",
    location: "Indianapolis, IN",
    start_date: "November 2017",
    end_date: "Present",
    keyPoints: [
      "Provides Developer Expierence Across All teams",
      "Maintains webpack bundler package for all projects",
      "Leading teams to develop enterprise applications for the state of Indiana",
    ],
    languages: "JavaScript, VueJS, Node, HTML, SCSS",
  },
  {
    title: "Senior Backend Web Developer",
    company: "Force Communications",
    start_date: "November 2015",
    location: "Indianapolis, IN",
    end_date: "November 2017",
    keyPoints: [
      "Develop multiple applications for client and internal usage simultaneously",
      "Build project requirements and timelines while working closely with the clients",
      "Responsible for building a team to use best practices of Agile, and software development",
    ],
    languages: "PHP, JavaScript, HTML, SCSS",
  },
  {
    title: "Software Engineer",
    company: "Patronpath / Verge Ventures",
    location: "Indianapolis, IN",
    start_date: "November 2014",
    end_date: "November 2015",
    keyPoints: [
      "Maintenance and Support for Legacy online ordering platform",
      "Lead a small agile team to develop a new online ordering platform with Laravel",
      "Utilize web sockets to create and report incidents",
    ],
    languages: "PHP, JavaScript, HTML, SCSS",
  },
  {
    title: "Web Developer",
    company: "NTSupply",
    location: "Greenwood, IN",
    start_date: "May 2014",
    end_date: "November 2014",
    keyPoints: [
      "Maintain support for legacy code",
      "Develop custom content management system",
      "Design email integration to Bronto’s services for DiscountFilters.com",
      "Utilize a profiler to enhance the ability to debug and improve performance of the PHP applications",
    ],
    languages: "PHP, JavaScript, HTML, CSS",
  },
  {
    title: "Web Developer",
    company: "Purdue University – ITaP Research Computing",
    location: "West Lafayette, IN",
    start_date: "September 2013",
    end_date: "May 2014",
    keyPoints: [
      "Develop tools for driNET.hubzero.org",
      "Collaborate with scientists to design and format data",
    ],
    languages: "",
  },
  {
    title: "Web Developer",
    company: "Envision Center",
    location: "West Lafayette, IN",
    start_date: "September 2013",
    end_date: "May 2014",
    keyPoints: [
      "Help customers to reach their goals, expectations, and deadlines",
      "Work with ArcGIS JavaScript API to develop interactive maps for Tipping Point",
    ],
    languages: "",
  },
  {
    title: "Senior Developer",
    company: "ResNet",
    location: "West Lafayette, IN",
    start_date: "August 2010",
    end_date: "August 2013",
    keyPoints: [
      "Train developers on standard documentation practices, Model View Controller Framework, Object Oriented Programing, PHP, MySQL, JQuery, and server side management",
      "Lead the design, development, and successful launch of the completely rewritten web applications TRAMS6 & MyResNet, whichserves over 10,000 students and staff",
      "Administrate multiple Apache web and MySQL databases used for development and production environments",
    ],
    languages: "",
  },
];
